docs: add join built-in
reviewpad/docs pull request #152
Opened 2022-12-15 15:20 UTC by zoldater

## Description

This pull request introduces documentation for the built-in function $join().

## Related issue

## Checklist

- [ x] I have performed a self-review of my code
- [ x] I have run `yarn build` without any errors

## Code review and merge strategy (ship/show/ask)

- [ x] Ask: this pull request requires a code review before merge

2022-12-15 15:58 UTC, marcelosousa commented
Hi @zoldater - many thanks for this PR! Could you please update your branch with the latest main and ensure that we don't have any "Merge commits" from main. We want to keep the history of the PR clean :-) Thanks! 
PS: Please take a look at the formatting of the description as well!

2022-12-16 09:56 UTC, zoldater commented
Hi @marcelosousa - markdown in description was fixed, branch was updated with rebase. Thanks for your attentiveness!

2022-12-19 11:52 UTC, ferreiratiago requested changes
Thanks for the pull request @zoldater I have added some suggestions.

2022-12-19 11:52 UTC, ferreiratiago commented on docs/guides/built-ins/functions/join/example.yml
> +      - '$comment($sprintf("This pull request contains unsecure changes. Please, request 1:1 with Security team: %s", [join($team("security"))]))'
The idea behind all `example.yml` is to have a fully working example. This means that anyone could copy the whole example, paste it on their `reviewpad.yml` and it's working :)

This is not the case for this example. Because the rule `unsecure-changes` is not defined. Also, the new `join` built-in is missing the `$`.

WDYT?
```suggestion
api-version: reviewpad.com/v3.x

workflows:
  - name: changes-on-security
    description: Warn when changes include security annotation
    if:
      - $hasAnnotation("security")
    then:
      - '$warn($sprintf("This pull request contains security changes. Please, request a 1:1 with security team: %s", [$join($team("security"))]))'
```

2022-12-19 11:52 UTC, ferreiratiago commented on docs/guides/built-ins/functions/join/index.mdx
> +| `separator` (optional) | literal    | The separator to put between elements. |
Let's use the type `string` here.

```suggestion
| `elements`             | \[]string | The array to join.                         |
| `separator` (optional) | string    | The separator to put between the elements. |
```

2022-12-19 11:52 UTC, ferreiratiago commented on docs/guides/built-ins/functions/join/index.mdx
> +| `string` | The concatenated string of elements with separator between. |
```suggestion
| `string` | The concatenated string of elements with the separator between them. |
```

2022-12-19 11:52 UTC, ferreiratiago commented on docs/guides/built-ins/functions/join/index.mdx
> +$join(["alice", "bob"], ", ")   # alice, bob
```suggestion
$join(["alice", "bob"])         # "alice bob"
$join(["alice", "bob"], ", ")   # "alice, bob"
```

2022-12-19 11:52 UTC, ferreiratiago commented on docs/guides/built-ins/functions/join/index.mdx
> +<CodeBlock language="yml">{Example}</CodeBlock>
```suggestion
<CodeBlock language="yml" name="reviewpad.yml">{Example}</CodeBlock>
```

2022-12-19 15:36 UTC, zoldater commented on docs/guides/built-ins/functions/join/index.mdx
> +| `separator` (optional) | literal    | The separator to put between elements. |
Fixed

2022-12-19 15:36 UTC, zoldater commented on docs/guides/built-ins/functions/join/index.mdx
> +| `string` | The concatenated string of elements with separator between. |
Fixed

2022-12-19 15:36 UTC, zoldater commented on docs/guides/built-ins/functions/join/index.mdx
> +$join(["alice", "bob"], ", ")   # alice, bob
Fixed

2022-12-19 15:36 UTC, zoldater commented on docs/guides/built-ins/functions/join/index.mdx
> +<CodeBlock language="yml">{Example}</CodeBlock>
Fixed

2022-12-20 13:32 UTC, ferreiratiago approved these changes

2022-12-21 13:19 UTC, merged