Fix/metrics report typo
reviewpad/docs pull request #154
Opened 2022-12-19 18:12 UTC by adrianoapmartins

## Description

Currently there is a typo on the Metrics report definitions:

> Coding time: the amount of time between the first commit and **the pull request was created**.
> Pickup time: the amount of time between **the when the pull request was created** and the first review was given.
> Review time: the amount of time between the first review and **the pull request was merged**.

## Related issue

## Checklist

- [x] I have performed a self-review of my code
- [ ] I have run `yarn build` without any errors - I could not do it (git problems on my local machine)

## Code review and merge strategy (ship/show/ask)

- [x] Ask: this pull request requires a code review before merge

2022-12-20 14:58 UTC, ferreiratiago requested changes

2022-12-20 14:58 UTC, ferreiratiago commented on docs/guides/reports/index.mdx
> +- **Review time**: the amount of time between the first review start and the pull request merge.
With the help of chatGPT
```suggestion
- **Coding time**: the time elapsed between the first commit and the creation of the pull request.
- **Pickup time**: the time elapsed between the creation of the pull request and the submission of the first review.
- **Review time**: the time elapsed between the submission of the first review and the merge of the pull request.
```

WDYT?

2022-12-21 09:54 UTC, merged

2022-12-21 10:15 UTC, adrianoapmartins commented on docs/guides/reports/index.mdx
> +- **Review time**: the amount of time between the first review start and the pull request merge.
Sounds very good. Did you accept the changes before merging?

2022-12-21 10:17 UTC, adrianoapmartins commented
@ferreiratiago shouldn't it be a AWS Amplify preview of the website here in this PR?