feat: approve built-in
reviewpad/docs pull request #193
Opened 2023-02-13 10:13 UTC by shay2025

## Description

This pull request adds the documentation for the `$approve` built-in developed in https://github.com/reviewpad/reviewpad/pull/685

## Related issue

Closes #191 

## Checklist

- [x] I have performed a self-review of my code
- [x] I have run `yarn build` without any errors

## Code review and merge strategy (ship/show/ask)

- [x] Ask: this pull request requires a code review before the merge

2023-02-13 16:19 UTC, zolamk commented on docs/guides/built-ins/actions/approve/index.mdx
> +This buit-in is **not** available for [`issue`](/guides/syntax#workflow).
```suggestion
This built-in is **not** available for [`issue`](/guides/syntax#workflow).
```

2023-02-13 16:20 UTC, zolamk approved these changes
Aside from the minor spelling comment, LGTM

2023-02-13 17:22 UTC, ferreiratiago requested changes

2023-02-13 17:22 UTC, ferreiratiago commented on docs/guides/built-ins/actions/approve/index.mdx
> +- the last submitted review has a different body or isn't an approval.
Following this comment https://github.com/reviewpad/reviewpad/pull/685#discussion_r1104777095 this conditions does not apply anymore.

2023-02-13 17:22 UTC, ferreiratiago commented on docs/guides/built-ins/actions/approve/example.yml
> +      - $hasFileName("README.md")
I would suggest using the built-in `hasFileExtensions`. This is because the built-in `hasFileName` will be true if the pull request has a change to the file `README.md` regardless of other changes.

2023-02-13 17:22 UTC, ferreiratiago commented on docs/guides/built-ins/actions/approve/example.yml
> +      - $approve("This pull request only contains trivial changes")
Sounds like a good example to use `LTGM` :)

```suggestion
      - $approve("LGTM")
```

2023-02-13 23:22 UTC, ferreiratiago requested changes
Can we please update the documentation for the built-in `review` with the list of the conditions in which the review runs? This is because we are updating the built-in behavior in pull request https://github.com/reviewpad/reviewpad/pull/685

2023-02-14 11:16 UTC, ferreiratiago approved these changes

2023-02-14 11:16 UTC, merged