docs: adds documentation for assign code author reviewer
reviewpad/docs pull request #194
Opened 2023-02-14 12:45 UTC by zolamk

## Description
Adds documentation for `$assignCodeAuthorReviewer` built-in.

## Related issue

Closes #192 

## Checklist

- [x] I have performed a self-review of my code
- [x] I have run `yarn build` without any errors

## Code review and merge strategy (ship/show/ask)

- [x] Ask: this pull request requires a code review before merge

2023-02-14 13:44 UTC, shay2025 requested changes
Minor suggestions 🙂

2023-02-14 13:44 UTC, shay2025 commented on docs/guides/built-ins/actions/assignCodeAuthorReviewer/index.mdx
> +However, if the pull request already has a reviewer, nothing happens. This is to prevent adding a reviewer each time the pull request is updated.
Maybe we could take advantage of the definition provided in https://github.com/reviewpad/reviewpad/issues/678.
WDYT @ferreiratiago ?
```suggestion
Intelligently assigns the most relevant and available reviewer to the pull request.

The relevancy is based on the code ownership information available on the impacted source files. The more lines of code are owned by a reviewer on the impacted source files, the more relevant this reviewer is for the pull request.

The availability is based on the number of open pull requests per reviewer. Above a configurable threshold (`max_reviews`), the reviewer is considered unavailable.

The assigned reviewer will always be different than the pull request's author.

If no relevant reviewer is available for this pull request, a random user of the GitHub organization will be assigned as the reviewer.

If the pull request already has a reviewer, no action will be taken.

When there is no reviewer to assign to, an error is returned.
```

2023-02-14 13:44 UTC, shay2025 commented on docs/guides/built-ins/actions/assignCodeAuthorReviewer/index.mdx
> +| `excluded_reviewers` (optional) | []string | A list of usernames to exclude from review requests.                      |
Minor suggestion:
```suggestion
| Parameter                       | Type     | Description                                                                       |
| :------------------------------ | :--------| :-------------------------------------------------------------------------------- |
| `max_reviews` (optional)        | int      | The maximum number of open reviews a user can have. By default, no limit is set.  |
| `excluded_reviewers` (optional) | []string | List of usernames to exclude from review requests.                                |
```

2023-02-14 13:44 UTC, shay2025 commented on docs/guides/built-ins/actions/assignCodeAuthorReviewer/example.yml
> +      - $assignCodeAuthorReviewer()
Maybe we could present some arguments in this example since we don't in https://github.com/reviewpad/docs/pull/194/files#diff-119144fa4cd4ae9c48e314d8aa4ce22f664694e46a66dc43500e30de11dd4587R29
```suggestion
      - $assignCodeAuthorReviewer(2, ["john", "marie"])
```

2023-02-14 15:34 UTC, shay2025 requested changes
Minor change.

2023-02-14 15:34 UTC, shay2025 commented on docs/guides/built-ins/actions/assignCodeAuthorReviewer/index.mdx
> +| `total_required_reviewers` (optional) | int      | The total number of required reviewers.                                          |
```suggestion
| `total_required_reviewers` (optional) | int       | The total number of required reviewers. By default, it is one.                    |
```

2023-02-14 16:18 UTC, shay2025 commented on docs/guides/built-ins/actions/assignCodeAuthorReviewer/index.mdx
> +| `max_reviews` (optional)              | int      | The maximum number of open reviews a user can have. By default, no limit is set. |
What do you think?
```suggestion
| `max_reviews` (optional)              | int       | The maximum number of open pull requests that a single user can be responsible for reviewing.  |
```

2023-02-14 17:30 UTC, shay2025 approved these changes
Minor suggestion

2023-02-14 17:30 UTC, shay2025 commented on docs/guides/built-ins/actions/assignCodeAuthorReviewer/index.mdx
> +| `max_reviews` (optional)              | int      | The maximum number of open pull requests that a single user can be responsible for reviewing |
Just missing a dot 🙂 
```suggestion
| `max_reviews` (optional)              | int      | The maximum number of open pull requests that a single user can be responsible for reviewing. |
```

2023-02-15 10:49 UTC, ferreiratiago approved these changes

2023-02-15 10:50 UTC, merged