docs: add documentation for hasAnyCheckRunCompleted built-in function
reviewpad/docs pull request #229
Opened 2023-03-03 03:36 UTC by zolamk

## Description

## Related issue

Closes #228 

## Checklist

- [x] I have performed a self-review of my code
- [x] I have run `yarn build` without any errors

## Code review and merge strategy (ship/show/ask)

- [x] Ask: this pull request requires a code review before merge

2023-03-03 16:26 UTC, shay2025 requested changes
Some suggestions

2023-03-03 16:26 UTC, shay2025 commented on docs/guides/built-ins/functions/hasAnyCheckRunCompleted/index.mdx
> +The `check_conclusions` parameter can contain one of `action_required`, `cancelled`, `failure`, `neutral`, `success`, `skipped`, `stale` or `timed_out`.
WDYT?
```suggestion
Checks whether any check runs for a pull request have been completed with the provided conclusions.

If the `check_runs_to_ignore` parameter is provided, any check runs that have a name included in the parameter will be ignored.

If the `check_conclusions` parameter is provided, only consider check runs that have been completed with one of the provided conclusions will be considered.

The `check_conclusions` parameter accepts the following values: `action_required`, `cancelled`, `failure`, `neutral`, `success`, `skipped`, `stale`, and `timed_out`.
```

2023-03-03 16:26 UTC, shay2025 commented on docs/guides/built-ins/functions/hasAnyCheckRunCompleted/example.yml
> +      - $comment("All checks must complete successfully")
WDYT?
```suggestion
      - $review("REQUEST_CHANGES", "Pull request checks are failing. Please fix them.")
```

2023-03-06 09:07 UTC, shay2025 approved these changes

2023-03-06 17:03 UTC, ferreiratiago commented on docs/guides/built-ins/functions/hasAnyCheckRunCompleted/index.mdx
> +---
Please remove the work around. This is only needed for pages with links.

2023-03-06 17:03 UTC, ferreiratiago commented on docs/guides/built-ins/functions/hasAnyCheckRunCompleted/index.mdx
> +| Parameter                                | Type       | Description                                             |
Please check the formatting here.

2023-03-06 17:49 UTC, ferreiratiago approved these changes

2023-03-06 18:38 UTC, merged