feat: update assignReviewer docs with policy
reviewpad/docs pull request #78
Opened 2022-10-10 16:23 UTC by shay2025

## Description

This pull request updates the documentation for `$assignReviewer` with the parameter `policy` that is implemented in the pull request https://github.com/reviewpad/reviewpad/pull/382

## Checklist

- [ ] I have performed a self-review of my code

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-10-10 16:24 UTC, shay2025 commented
This pull request needs to be merged before https://github.com/reviewpad/reviewpad/pull/382

2022-10-12 09:42 UTC, ferreiratiago requested changes
Can you please review the uses cases to make sure no updates are required?

2022-10-12 09:42 UTC, ferreiratiago commented on docs/guides/built-ins/actions/assignReviewer/index.mdx
> +
```suggestion
Reviewers can be assigned following one of the described policies:
- `random`: the reviewers are chosen in a random manner;
- `round-robin`: the reviewers are chosen following the `round-robin` algorithm;
- `reviewpad`: the reviewers are chosen based on the total number of pull requests assigned to them. The smaller the number of pull requests assigned to a reviewer, the greater the probability of being picked.
```

2022-10-12 09:42 UTC, ferreiratiago commented on docs/guides/built-ins/actions/assignReviewer/index.mdx
> +| `total` (optional)  | int       | The total of reviewers to assign. By default, assigns to all reviewers.                         |
For the description:
```
The total number of reviewers to assign to. By default, it assigns to all reviewers.
```

2022-10-12 09:42 UTC, ferreiratiago commented on docs/guides/built-ins/actions/assignReviewer/index.mdx
> +| `policy` (optional) | string    | The arrangement of choosing the reviewers to assign. By default, the policy is `reviewpad`. |
For the description: 
```
The policy followed for reviewer assignment. By default, the policy is `reviewpad`.
```

2022-10-12 11:05 UTC, merged