feat: deleteHeadBranch built-in documentation
reviewpad/docs pull request #84
Opened 2022-10-17 15:22 UTC by shay2025

## Description

This pull request adds the documentation for the `$deleteHeadBranch` action built-in.

## Checklist

- [x] I have performed a self-review of my code

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-10-19 11:25 UTC, ferreiratiago requested changes

2022-10-19 11:25 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The action will only happen if and when the pull request is closed or merged.
> 
```suggestion
The action is only executed if the pull request is either closed or merged.
```

2022-10-19 11:25 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The branch is deleted even if another pull request depends on the head branch. Therefore, GitHub will close the dependent pull requests.
Can you please clarify this `Therefore, GitHub will close the dependent pull requests.`?

If I have PR1 from A -> B and PR2 from C -> A. What happens to PR2 if I merge PR1 and delete the head branch?

2022-10-19 11:25 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +This only works if the branch is stored in the same repository as the pull request target, i.e., if the pull request comes from the same repository and not from a fork.
This sentence can be a warning saying `This builtin does not work on pull request from forks.` WDYT?

2022-10-19 11:38 UTC, shay2025 commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The branch is deleted even if another pull request depends on the head branch. Therefore, GitHub will close the dependent pull requests.
@ferreiratiago The PR2 is closed.

2022-10-19 11:39 UTC, shay2025 commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +This only works if the branch is stored in the same repository as the pull request target, i.e., if the pull request comes from the same repository and not from a fork.
It seems right.

2022-10-20 09:16 UTC, ferreiratiago approved these changes
Some minor changes. Please have a look.

2022-10-20 09:16 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/example.yml
> +    description: Merge and delete head branch if patch only contains changes to files with extension .md
```suggestion
    description: Merge and delete head branch if all changes are to markdown files
```

2022-10-20 09:16 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The branch is deleted even if another pull request depends on the head branch. Therefore, GitHub will close the dependent pull requests.
I would suggest a warning for this.

```suggestion
:::warning WARNING

Deleting a branch will cause all pull requests that have the deleted branch as head to also be closed.

:::
```

2022-10-20 09:27 UTC, shay2025 commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The branch is deleted even if another pull request depends on the head branch. Therefore, GitHub will close the dependent pull requests.
This warning is not correct because pull requests that have the deleted branch as head OR base will be closed.

2022-10-20 09:28 UTC, shay2025 commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The branch is deleted even if another pull request depends on the head branch. Therefore, GitHub will close the dependent pull requests.
Also should I put both these warnings https://github.com/reviewpad/docs/pull/84#discussion_r999311426 together in one warning message?

2022-10-20 09:35 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The branch is deleted even if another pull request depends on the head branch. Therefore, GitHub will close the dependent pull requests.
> This warning is not correct because pull requests that have the deleted branch as head OR base will be closed.

Ok. Then we can update the info to be correct :)

> Also should I put both these warnings [#84 (comment)](https://github.com/reviewpad/docs/pull/84#discussion_r999311426) together in one warning message?

I would try to do that before placing them in different warning messages. The important thing is to make it clear :)

2022-10-20 10:21 UTC, ferreiratiago approved these changes

2022-10-20 10:21 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +Deleting a branch will cause all pull requests that have the deleted branch as head or base to also be closed.
```suggestion
Deleting a branch will cause all pull requests that have the deleted branch as head or base to be closed.
```

2022-10-20 10:21 UTC, ferreiratiago commented on docs/guides/built-ins/actions/deleteHeadBranch/index.mdx
> +The action is only executed if the pull request is either closed or merged.
```suggestion
This built-in is only executed if the pull request is either closed or merged.
```

2022-10-20 11:19 UTC, merged